const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const asset=name=>fs.readFileSync('app/src/main/assets/'+name,'utf8');
const loader=asset('feature-loader.js'),group=asset('v064-group-session.js'),queue=asset('v070-beta-queue.js');
const ui=asset('v071-shared-ui-authority.js'),native=fs.readFileSync('app/src/main/java/pl/edwin/trener2/LocalSessionManager.java','utf8');
assert(loader.includes("['0.9.0','v090-recipes.js']"));
assert(loader.includes("['0.9.2','v083-shared-controller.js']"));
assert(group.includes('protocolMeta()'),'main participant protocol data must survive upgrade');
assert(group.includes('singleController:true'),'single device mode capability must survive');
assert(queue.includes('submitControlledRecord=submitControlledRecord'),'main host controlled record must be registered');
assert(queue.includes('state.skipControlledRest='));
assert(ui.includes('isLocalController'),'main shared UI control must remain available');
assert(native.includes('matchesHandshake(hello, expectedCode, appVersion)'),'mixed-version native socket rejection');
const window={Android:{getAppVersion:()=> '0.9.2'},TrenerGroup:{participants:[],deviceId:'device1'}};
const document={readyState:'loading',addEventListener(){}};
const localStorage={getItem(){return null;},setItem(){}};
vm.runInNewContext(asset('v082-shared-guard-progress.js'),{window,Android:window.Android,document,localStorage},{timeout:2000});
const guard=window.TrenerSharedProtocol083;
assert(guard&&guard.current===2);
assert.equal(guard.compatible({version:'0.9.2',protocolVersion:2}),true);
assert.equal(guard.compatible({version:'0.9.1',protocolVersion:2}),false);
assert.equal(guard.compatible({version:'0.8.3',protocolVersion:2}),false);
assert.equal(guard.compatible({version:'0.9.2',protocolVersion:1}),true);
vm.runInNewContext(asset('v083-shared-controller.js'),{window,document,localStorage},{timeout:2000});
const control=window.TrenerSharedControl083;
assert(control&&control.protocolVersion===2);
assert.equal(typeof control.setModeHost,'function');
assert.equal(typeof control.requestTransfer,'function');
assert.equal(typeof control.submitControlledSet,'function');
assert.equal(typeof control.allSupportSingle,'function');
const gradle=fs.readFileSync('app/build.gradle','utf8');
assert(gradle.includes("versionName '0.9.3'")&&gradle.includes('versionCode 93'));
console.log('Main reconciliation 0.9.2: recipes, native guard, shared-controller and protocol 2 kept OK');
