'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const dir='app/src/main/assets/';
const root={};
let jobs=[],writes=0;
const store=new Map();
const storage={getItem:k=>store.get(k)||null,setItem:(k,v)=>{writes++;store.set(k,v);}};
root.Android={printRecipe:(html,title)=>jobs.push({html,title})};
vm.runInNewContext(fs.readFileSync(dir+'v090-recipes.js','utf8'),{window:root,localStorage:storage},{timeout:3000});
vm.runInNewContext(fs.readFileSync(dir+'v093-recipe-diet.js','utf8'),{window:root,localStorage:storage},{timeout:3000});
vm.runInNewContext(fs.readFileSync(dir+'v096-recipe-print.js','utf8'),{window:root,localStorage:storage},{timeout:3000});
const recipe=root.TrenerRecipes090.RECIPES[0],p=root.TrenerRecipePrint096;
const base=p.printMeal(recipe);
assert.equal(jobs.length,1);
assert.equal(jobs[0].title,recipe.name);
assert.match(jobs[0].html,/Składniki/);
assert.match(jobs[0].html,/Przygotowanie/);
assert.match(jobs[0].html,/<html lang="pl">/);
assert.equal(writes,0,'print must not change Diet or recipe settings');
const larger=p.printMeal(recipe,recipe.items.map((x,i)=>i===0?x[1]*2:x[1]));
assert(larger.kcal>base.kcal,'printed kcal must track current grams');
assert.equal(jobs.length,2);
assert(jobs[1].html.includes(String(recipe.items[0][1]*2)+' g'));
const malicious={...recipe,name:'Test <script>alert(1)</script>'};
p.printMeal(malicious);
assert(!jobs[2].html.includes('<script>'));
assert(jobs[2].html.includes('&lt;script&gt;'));
assert.throws(()=>p.printMeal(recipe,[0]),/gramatura/);
assert.equal(jobs.length,3);
assert.equal(writes,0);
const java=fs.readFileSync('app/src/main/java/pl/edwin/trener2/MainActivity.java','utf8');
assert(java.includes('public void printRecipe(String html, String title)'));
assert(fs.readFileSync('app/src/main/java/pl/edwin/trener2/RecipePrintManager.java','utf8').includes('createPrintDocumentAdapter'));
assert(fs.readFileSync(dir+'feature-loader.js','utf8').includes("['0.9.5.2','v096-recipe-print.js']"));
assert(fs.readFileSync('app/build.gradle','utf8').includes("versionName '0.9.5.2'"));
console.log('Recipe printing: library, live grams, escaped HTML, native bridge, no Diet writes OK');
