const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const read=p=>fs.readFileSync('app/src/main/assets/'+p,'utf8');
const root={},memory=new Map();
const original={version:1,targets:{kcal:2300,protein:140,carbs:276,fat:65},
 meals:[{id:'legacy',date:'2026-09-21',name:'Rogalik',type:'breakfast',
  kcal:272,protein:3.4,carbs:25.8,fat:16.8,createdAt:1}],shopping:[{name:'Mleko'}]};
memory.set('trainer3.diet.v076',JSON.stringify(original));
memory.set('trainer2.recipes.v1',JSON.stringify({schemaVersion:1,profile:{age:34,weight:70}}));
memory.set('trainer3.photos',JSON.stringify([{id:'picture',data:'base64'}]));
const localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,String(v))};
let renders=0,syncs=0,writes=0;
root.TrenerDiet076={load:()=>JSON.parse(memory.get('trainer3.diet.v076')),
 getDate:()=> '2026-09-21',render:()=>renders++};
root.TrenerWidget077={sync:()=>syncs++};
const guarded={getItem:localStorage.getItem,setItem:(k,v)=>{writes++;localStorage.setItem(k,v)}};
vm.runInNewContext(read('v090-recipes.js'),root,{timeout:3000});
vm.runInNewContext(read('v093-recipe-diet.js'),{window:root,localStorage:guarded},{timeout:3000});
const api=root.TrenerRecipeDiet093;
assert(api,'recipe bridge must load');
assert.equal(root.TrenerRecipes090.RECIPES.length,50);
assert.equal(writes,0,'loading a recipe never touches old Diet');
const r=root.TrenerRecipes090.RECIPES.find(x=>x.id==='l1');
const personalized=root.TrenerRecipes090.personalized(r,{kcal:800,protein:65,carbs:88,fat:20});
const entry={...personalized,name:r.name,type:r.type,recipeId:r.id};
const preview=api.prepare(entry);
assert.equal(writes,0,'previews do not log food');
assert.equal(preview.ingredients.length,r.items.length);
assert.equal(preview.recipeId,'l1');
assert.equal(preview.ingredients[0].base100.protein,root.TrenerRecipes090.FOODS[preview.ingredients[0].key][2]);
assert.throws(()=>api.saveApproved(preview,'2026-09-21',false),/zatwierdź/);
assert.equal(writes,0,'no write without explicit confirmation');
assert.throws(()=>api.prepare(entry,[0]),/gramatura/);
assert.throws(()=>api.prepare(entry,[-5]),/gramatura/);
assert.throws(()=>api.prepare(entry,[10001]),/gramatura/);
assert.equal(api.validDay('2026-02-30'),false);
assert.equal(api.validDay('2026-09-21'),true);
assert.throws(()=>api.saveApproved(preview,'2026-02-30',true),/data/);
const grams=entry.items.map(x=>x.grams);
grams[0]*=2;
const changed=api.prepare(entry,grams);
assert(changed.kcal>preview.kcal,'grams affect calories');
assert(changed.protein>preview.protein,'grams affect protein');
for(const field of ['kcal','protein','carbs','fat'])
 assert(Math.abs(changed[field]-Math.round(changed.ingredients.reduce((v,x)=>v+x[field],0)*10)/10)<0.01);
const saved=api.saveApproved(changed,'2026-09-21',true);
assert.equal(writes,1,'exactly one Diet write');
assert.equal(renders,1);assert.equal(syncs,1);
const after=JSON.parse(memory.get('trainer3.diet.v076'));
assert.equal(after.version,1,'old schema preserved');
assert.equal(after.meals.length,2,'single composite record');
assert.deepEqual(after.meals[0],original.meals[0],'historical meal unchanged');
assert.deepEqual(after.targets,original.targets,'old targets unchanged');
assert.deepEqual(after.shopping,original.shopping,'shopping unchanged');
assert.equal(after.meals[1].id,saved.id);
assert.equal(after.meals[1].date,'2026-09-21');
assert.equal(after.meals[1].type,'lunch');
assert.equal(after.meals[1].ingredients[0].grams,grams[0]);
assert.equal(memory.get('trainer3.photos'),JSON.stringify([{id:'picture',data:'base64'}]));
assert.equal(memory.get('trainer2.recipes.v1'),JSON.stringify({schemaVersion:1,profile:{age:34,weight:70}}));
const plain=root.TrenerRecipes090.RECIPES.find(x=>x.id==='b1');
const fromLibrary=api.prepare({...root.TrenerRecipes090.nutrition(plain,1),
 name:plain.name,type:plain.type,recipeId:plain.id});
assert.equal(fromLibrary.name,plain.name);assert.equal(fromLibrary.type,'breakfast');
const loader=read('feature-loader.js');
assert(loader.includes("['0.9.5','v093-recipe-diet.js']"));
const old=fs.readFileSync('app/src/main/assets/v076-diet.js','utf8');
assert(old.includes("const KEY='trainer3.diet.v076'"));
const v=fs.readFileSync('app/build.gradle','utf8');
assert(v.includes("versionName '0.9.5'")&&v.includes('versionCode 95'));
console.log('Recipe-to-Diet 0.9.5: confirmation, ingredients, gram scaling, one record and legacy data OK');
